### PR TITLE
[W5.4r][W14-A1]Chua Wei Wen

### PR DESCRIPTION
**Pull request by chuaweiwen**
Added sort command, updated the user guide, added sorting tests.

### CODE REVIEW

**Comment by chuaweiwen** [comment]
Hi, I can't find the input.txt and expected.txt for the I/O test on level 3.

**Comment by chuaweiwen** [comment]
@okkhoy Hi, can you review this PR? Thank you.

**Review by okkhoy — COMMENTED** [review]
This is a good attempt.

**Comment by okkhoy** [comment]
@chuaweiwen Nothing much to review here. You have updated all the required aspects of implementing a new feature. Please ack and close this PR.

**Pull request closed without merging**
